
[tools]
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.setup]
description = "Install dependencies from pyproject.toml (locked)"
run = [
    "uv python install 3.14",
    "uv sync"
]

[tasks.run]
description = "Universal runner for python scripts"
run = "uv run python {{config.task.name}}.py"
