[tools]
bun = "latest"
node = "latest"
python = "latest"
go = "latest"
rust = "latest"
pnpm = "latest"
java = "temurin-21"

[settings]
trusted_config_paths = ["~/.config"]
experimental = true
jobs = 5

# python_venv_auto_create = true
